type: bigquery
method: service-account
keyfile: /opt/airflow/dbt/keyfile.json

dbt_modeling:
  outputs:
    dev:
      dataset: jcdeol3_capstone3_hafizh
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: purwadika
      threads: 1
      type: bigquery
  target: dev